# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Running Checkov Scan!"
    sudo apt-get install software-properties-common
    sudo add-apt-repository ppa:deadsnakes/ppa
    sudo apt install python3-pip
    sudo apt-get install python3-testresources
    sudo pip3 install checkov
    checkov -d hari-krishnankannan/TfModules --framework terraform --external-checks-dir custom-checks/terraform --skip-check CKV_AZURE_6
  displayName: 'Terraform code scan using Checkov'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    allowTelemetryCollection: true
- task: TerraformCLI@0
  inputs:
    command: 'plan'
    environmentServiceName: 'Azurek8sconnection'
    providerAzureRmSubscriptionId: 'b3c7ce23-4463-41af-b0ee-2aad6de340b9'
    allowTelemetryCollection: false
- task: TerraformCLI@0
  inputs:
    command: 'apply'
    environmentServiceName: 'Azurek8sconnection'
    providerAzureRmSubscriptionId: 'b3c7ce23-4463-41af-b0ee-2aad6de340b9'
    allowTelemetryCollection: false
