# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  displayName: 'Install checkov'
  inputs:
    targetType: 'inline'
    script: 'pip3 install checkov'

- task: Bash@3
  displayName: 'Checkov Static Code Analysis'
  inputs:
    targetType: 'inline'
    script: |
       mkdir checkov-report
       checkov -d . --skip-path ./*.json --check MEDIUM --output junitxml > $(System.DefaultWorkingDirectory)/checkov-report/TEST-checkov-report.xml  

- task: PublishTestResults@2
  displayName: 'Publish checkov Test Results'
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFile: '**/TEST-*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/checkov-report'
    mergeTestResults: false
    testRuntitle: CheckOV Scan
    failTaskOnFailedTests: false
    publishRunAttachements: true
- task: TerraformCLI@0
  inputs:
    command: 'init'
    allowTelemetryCollection: true
- task: TerraformCLI@0
  inputs:
    command: 'plan'
    environmentServiceName: 'Azurek8sconnection'
    providerAzureRmSubscriptionId: 'b3c7ce23-4463-41af-b0ee-2aad6de340b9'
    allowTelemetryCollection: false
- task: TerraformCLI@0
  inputs:
    command: 'apply'
    environmentServiceName: 'Azurek8sconnection'
    providerAzureRmSubscriptionId: 'b3c7ce23-4463-41af-b0ee-2aad6de340b9'
    allowTelemetryCollection: false
